pipeline:

  build_dependencies:
    image: alpine/helm:2.12.3
    commands:
    - helm init --client-only
    - helm dependency build incubator/kafka

  publish_charts:
    image: docker-registry.infra.redmart.com/devops/drone-helm-push:0.3.0
    pull: true
    charts:
    - stable/drone
    - stable/rabbitmq-ha
    - incubator/kafka
    helm_repo: https://charts.infra.redmart.com
    when:
      branch: [master]
      event: push
