pipeline:

  publish_charts:
    image: docker-registry.infra.redmart.com/devops/drone-helm-push:0.2.0-SNAPSHOT
    pull: true
    charts:
    - stable/drone
    - pepe
    helm_repo: https://charts.infra.redmart.com
    when:
      branch: [feature/publish-charts-ci] #Change before merge
      event: push
