kibana:
  env:
    ELASTICSEARCH_URL: http://http.default.svc.cluster.local:9200
  ingress:
    enabled: true
    hosts:
      - elk-k8s.alpha.redmart.com
      
    annotations:
      kubernetes.io/ingress.class: "internal-nginx"
elasticsearch:
  master:
    exposeHttp: true
    replicas: 2
    heapSize: "2Gi"
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      name: data
      size: "4Gi"
      storageClass: "rm-local-persistence-disks"
    antiAffinity: "soft"
    nodeAffinity: {}
    nodeSelector: {"redmart.com/role":"InfraStack_Elk"}
    tolerations: []
    resources:
      limits:
        cpu: "1.5"
        memory: "8Gi"
      requests:
        cpu: "1"
        memory: "7Gi"
    priorityClassName: ""
    podAnnotations:
      unit-name: "elk-data-node"
    updateStrategy:
      type: OnDelete

  data:
    exposeHttp: true
    replicas: 2
    heapSize: "4Gi"
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      name: data
      size: "100Gi"
      storageClass: "rm-local-persistence-disks"
    antiAffinity: "soft"
    nodeSelector: {"redmart.com/role":"InfraStack_Elk"}
    priorityClassName: ""
    podAnnotations:
      unit-name: "elk-data-node"
    resources:
      limits:
        cpu: "1.5"
        memory: "8Gi"
      requests:
        cpu: "1"
        memory: "7Gi"

  client:
    replicas: 2
    heapSize: "4Gi"
    antiAffinity: "soft"
    nodeSelector: {"redmart.com/role":"InfraStack_Elk"}
    resources:
      limits:
        cpu: "1.5"
        memory: "4Gi"
      requests:
        cpu: "1"
        memory: "4Gi"
    priorityClassName: ""
    podAnnotations:
      unit-name: "elk-data-node"
    podDisruptionBudget:
      enabled: false
      minAvailable: 1
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: "internal-nginx"
      path: /
      hosts:
        - es-k8s.alpha.redmart.com

logstash:
  enabled: true
  replicaCount: 2
  resources:
        limits:
          cpu: "1.5"
          memory: "8Gi"
        requests:
          cpu: "1"
          memory: "7Gi"
  nodeSelector: {"redmart.com/role":"InfraStack_Elk"}
  podAnnotations:
       unit-name: "elk-data-node"
  podLabels: 
       elk-service: "elk-logstash"
  persistence:
    enabled: true
    storageClass: "rm-local-persistence-disks"
    accessMode: ReadWriteOnce
    size: 30Gi
  podDisruptionBudget:
   maxUnavailable: 1
  elasticsearch:
    host: elastic-stack-elasticsearch-client

filebeat:
  enabled: false

fluentd:
  enabled: false

fluent-bit:
  enabled: false

fluentd-elasticsearch:
  enabled: false

nginx-ldapauth-proxy:
  enabled: false

elasticsearch-curator:
  enabled: false

elasticsearch-exporter:
  enabled: false